version: '3.8'

networks:
  ichub_films_net:
    external: true

services:

  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: films
    ports:
      - "6932:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d films"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ichub_films_net

  app:
    build:
      context: .
      dockerfile: deployment/local.Dockerfile
    container_name: app
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - /app/.venv # Изоляция от хоста
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ichub_films_net

volumes:
  postgres_data:
