"""

Revision ID: 383de11b642a
Revises: 58358eeeb88b
Create Date: 2026-06-05 19:42:00.214905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383de11b642a'
down_revision: Union[str, Sequence[str], None] = '58358eeeb88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_films_title'), 'films', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_title'), table_name='films')
    # ### end Alembic commands ###
